### ISSUE TITLE
Folder 06-EnvioCorreo - Uncaught TypeError: Cannot set property 'onclick' of undefined(…)

### ISSUE THREAD

**Issue by lmartinezg** [lmartinezg/betxlan-curso-php#2]
Error on javascript function:

window.onload = function() {
	document.mail_frm.enviar_btn.onclick = validarForm;
}

**Comment by luispuchades** [comment]
Issue read from Android GitHub app.

**Comment by lmartinezg** [comment]
Solved changing line in javascript code. See pull request for branch Ex06b.

Why didn't it work?

**Comment by luispuchades** [comment]
Alternative solution proposed in branch Ex06C including id names in input labels.

Input ID names were not being captured through JS Selectors (querySelector or getElementByID) from html/php file, so events could not be applied to defined JS functions.

Important to note: events prefixed with on- (onclick) must be applied in html/php text. Within JS code, events should not be used prefixed and should be applied with addEventListener (ie: document.addEventListener("click", functionToStart); )
